### ISSUE TITLE
Literally Unplayable

### ISSUE THREAD

**Issue by zaphim12** [gkgkgkgk/JetGame#2]
Thanks, 
Ray

**Comment by gkgkgkgk** [comment]
I apologize for the issues. It will be fixed in the next commit, guaranteed!
Thanks,
gkgkgkgk

**Comment by zaphim12** [comment]
The issue was only marginally improved by this commit.  It's still literally unplayable.  If this does not change I will leave a 1/5 star yelp review on your restaurant's page.
Thanks,
Ray

**Comment by zaphim12** [comment]
Boi, this shit ain't been fixed yet.  If the developer had any skill he would have had this issue resolved ages ago.  It's like he learned how to code from a monkey wearing diapers.  Have you seen his comments? they don't even make any sense.  The game looks like a powerpoint presentation from how low the framerate is.  Learn how to multi-thread bitch.  He probably thinks Plesmiograph tier-9 combustible machina lens is an appropriate substitute for a good EctoGen tier-8.  What a pleb.  Garfield is less lazy then this guy.
btw, nice graphics
